#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const cp = require('child_process');

function parseDotEnv(content) {
  const out = {};
  for (const line of String(content || '').split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith('#') || !t.includes('=')) continue;
    const idx = t.indexOf('=');
    const key = t.slice(0, idx).trim();
    let value = t.slice(idx + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function quoteEnvValue(value) {
  const str = String(value ?? '');
  if (!str) return '';
  if (/^[A-Za-z0-9_./:@+\-]+$/.test(str)) return str;
  return JSON.stringify(str);
}

function extractWpConfig(configPath) {
  const raw = fs.readFileSync(configPath, 'utf8');

  const readDefine = (key) => {
    const m = raw.match(new RegExp(`define\\(\\s*['\"]${key}['\"]\\s*,\\s*['\"]([^'\"]+)['\"]\\s*\\)`));
    return m ? m[1] : '';
  };

  const tablePrefix = (raw.match(/\$table_prefix\s*=\s*['\"]([^'\"]+)['\"]/) || [])[1] || 'wp_';

  return {
    dbName: readDefine('DB_NAME'),
    dbUser: readDefine('DB_USER'),
    dbPassword: readDefine('DB_PASSWORD'),
    dbHost: readDefine('DB_HOST') || 'localhost',
    tablePrefix,
  };
}

function queryWpOptions(wpConfig, optionNames) {
  const table = `${wpConfig.tablePrefix}options`;
  const quotedNames = optionNames.map((name) => `'${name.replace(/'/g, "''")}'`).join(',');
  const sql = `SELECT option_name, option_value FROM ${table} WHERE option_name IN (${quotedNames})`;

  const output = cp.execFileSync(
    'mysql',
    ['-h', wpConfig.dbHost, '-u', wpConfig.dbUser, '-N', '-B', '-e', sql, wpConfig.dbName],
    { env: { ...process.env, MYSQL_PWD: wpConfig.dbPassword } }
  ).toString();

  const result = {};
  for (const line of output.split(/\r?\n/)) {
    if (!line.trim()) continue;
    const idx = line.indexOf('\t');
    if (idx <= 0) continue;
    const key = line.slice(0, idx);
    const value = line.slice(idx + 1);
    result[key] = value;
  }
  return result;
}

function main() {
  const cwd = process.cwd();
  const projectRoot = path.basename(cwd) === 'catalog-unifier' ? path.dirname(cwd) : cwd;
  const unifierDir = path.join(projectRoot, 'catalog-unifier');
  const envPath = path.join(unifierDir, '.env');

  const wpConfigPath = process.env.WP_CONFIG_PATH || '/var/www/wp/wp-config.php';
  if (!fs.existsSync(wpConfigPath)) {
    throw new Error(`No existe wp-config.php en ${wpConfigPath}`);
  }

  const existing = fs.existsSync(envPath)
    ? parseDotEnv(fs.readFileSync(envPath, 'utf8'))
    : {};

  const wpConfig = extractWpConfig(wpConfigPath);
  const values = queryWpOptions(wpConfig, [
    'dmi_api_url',
    'dmi_username',
    'dmi_password',
    'megasur_feed_url',
  ]);

  const next = {
    ...existing,
    CATALOG_UNIFIER_DB_PATH: existing.CATALOG_UNIFIER_DB_PATH || './catalog-unifier/storage/unifier.db',
    CATALOG_UNIFIER_OUTPUT_DIR: existing.CATALOG_UNIFIER_OUTPUT_DIR || './catalog-unifier/output',
    MEGASUR_LOCAL_PATH: existing.MEGASUR_LOCAL_PATH || './storage/megasur/current.json',
    MEGASUR_FEED_URL: values.megasur_feed_url || existing.MEGASUR_FEED_URL || '',
    DMI_LOCAL_PATH: existing.DMI_LOCAL_PATH || '',
    DMI_API_URL: values.dmi_api_url || existing.DMI_API_URL || 'https://api.dmi.es',
    DMI_USERNAME: values.dmi_username || existing.DMI_USERNAME || '',
    DMI_PASSWORD: values.dmi_password || existing.DMI_PASSWORD || '',
    DMI_CACHE_PATH: existing.DMI_CACHE_PATH || './catalog-unifier/storage/dmi-current.json',
    DMI_CACHE_MAX_AGE_MINUTES: existing.DMI_CACHE_MAX_AGE_MINUTES || '60',
    UNIFIER_DEFAULT_MARGIN_PERCENT: existing.UNIFIER_DEFAULT_MARGIN_PERCENT || '20',
    UNIFIER_WEEKLY_MARGIN_PERCENT: existing.UNIFIER_WEEKLY_MARGIN_PERCENT || '10',
    UNIFIER_SHIPPING_FEE_EUR: existing.UNIFIER_SHIPPING_FEE_EUR || '5',
    UNIFIER_WC_URL: existing.UNIFIER_WC_URL || process.env.NEXT_PUBLIC_WC_URL || '',
    UNIFIER_WC_CONSUMER_KEY: existing.UNIFIER_WC_CONSUMER_KEY || process.env.WC_CONSUMER_KEY || process.env.WC_SERVER_CONSUMER_KEY || '',
    UNIFIER_WC_CONSUMER_SECRET: existing.UNIFIER_WC_CONSUMER_SECRET || process.env.WC_CONSUMER_SECRET || process.env.WC_SERVER_CONSUMER_SECRET || '',
    UNIFIER_WC_TIMEOUT_MS: existing.UNIFIER_WC_TIMEOUT_MS || '30000',
    UNIFIER_WC_CREATE_CATEGORIES: existing.UNIFIER_WC_CREATE_CATEGORIES || '1',
  };

  const lines = [
    '# Generated by catalog-unifier/src/tools/bootstrap-wp-env.js',
    '# Safe to edit manually after bootstrap.',
    '',
    'CATALOG_UNIFIER_DB_PATH=' + quoteEnvValue(next.CATALOG_UNIFIER_DB_PATH),
    'CATALOG_UNIFIER_OUTPUT_DIR=' + quoteEnvValue(next.CATALOG_UNIFIER_OUTPUT_DIR),
    '',
    'MEGASUR_LOCAL_PATH=' + quoteEnvValue(next.MEGASUR_LOCAL_PATH),
    'MEGASUR_FEED_URL=' + quoteEnvValue(next.MEGASUR_FEED_URL),
    '',
    'DMI_LOCAL_PATH=' + quoteEnvValue(next.DMI_LOCAL_PATH),
    'DMI_API_URL=' + quoteEnvValue(next.DMI_API_URL),
    'DMI_USERNAME=' + quoteEnvValue(next.DMI_USERNAME),
    'DMI_PASSWORD=' + quoteEnvValue(next.DMI_PASSWORD),
    'DMI_CACHE_PATH=' + quoteEnvValue(next.DMI_CACHE_PATH),
    'DMI_CACHE_MAX_AGE_MINUTES=' + quoteEnvValue(next.DMI_CACHE_MAX_AGE_MINUTES),
    '',
    'UNIFIER_DEFAULT_MARGIN_PERCENT=' + quoteEnvValue(next.UNIFIER_DEFAULT_MARGIN_PERCENT),
    'UNIFIER_WEEKLY_MARGIN_PERCENT=' + quoteEnvValue(next.UNIFIER_WEEKLY_MARGIN_PERCENT),
    'UNIFIER_SHIPPING_FEE_EUR=' + quoteEnvValue(next.UNIFIER_SHIPPING_FEE_EUR),
    '',
    'UNIFIER_WC_URL=' + quoteEnvValue(next.UNIFIER_WC_URL),
    'UNIFIER_WC_CONSUMER_KEY=' + quoteEnvValue(next.UNIFIER_WC_CONSUMER_KEY),
    'UNIFIER_WC_CONSUMER_SECRET=' + quoteEnvValue(next.UNIFIER_WC_CONSUMER_SECRET),
    'UNIFIER_WC_TIMEOUT_MS=' + quoteEnvValue(next.UNIFIER_WC_TIMEOUT_MS),
    'UNIFIER_WC_CREATE_CATEGORIES=' + quoteEnvValue(next.UNIFIER_WC_CREATE_CATEGORIES),
    '',
  ];

  fs.writeFileSync(envPath, lines.join('\n'), 'utf8');

  const summary = {
    envPath,
    dmiApiConfigured: Boolean(next.DMI_API_URL),
    dmiUserConfigured: Boolean(next.DMI_USERNAME),
    dmiPassConfigured: Boolean(next.DMI_PASSWORD),
    megasurFeedConfigured: Boolean(next.MEGASUR_FEED_URL || next.MEGASUR_LOCAL_PATH),
    wcConfigured: Boolean(next.UNIFIER_WC_URL && next.UNIFIER_WC_CONSUMER_KEY && next.UNIFIER_WC_CONSUMER_SECRET),
  };

  console.log(JSON.stringify(summary, null, 2));
}

main();
